### ISSUE TITLE
Should I add +1 to my custom num of classes on the RetinaNet head?

### ISSUE THREAD

**Issue by sarmientoj24** [benihime91/pytorch_retinanet#3]
The config.py has this

```
# ----------------------------------------------------------------------------- #
# RetinaNet Head
# ----------------------------------------------------------------------------- #
NUM_CLASSES: int = 90
# This is the number of foreground classes.
```

If I have 17 classes, do I input 17 or 18 there?

**Comment by benihime91** [comment]
If you have 17 classes input 17 there assuming there is no background class, also the integrer label for the classes should start from 1 . 0 is reserved for the backgorund class. Check the [demo notebook](https://github.com/benihime91/pytorch_retinanet/blob/master/demo.ipynb) or [source](https://github.com/benihime91/pytorch_retinanet/blob/master/retinanet/models.py) for clarification ...

Hope this helps !
