### ISSUE TITLE
min object size

### ISSUE THREAD

**Issue by natxopedreira** [benihime91/pytorch_retinanet#5]
Whats the min bounding box size the model can detect and that i can use to train?

Thanks!

**Comment by benihime91** [comment]
@natxopedreira Its going to depend upon you anchors. For the default retinanet anchors you can check this discussion : 
https://github.com/fizyr/keras-retinanet/issues/202

**Comment by natxopedreira** [comment]
Thank you!! so i see 32x32 and if small scale images a bit up

I will try
