### ISSUE TITLE
Not able to import pytorch_lightning in colab

### ISSUE THREAD

**Issue by alankritmishra** [benihime91/pytorch_retinanet#6]
Whenever I am running the below code in Colab:
`import pytorch_lightning as pl`

Its is showing below error:
_ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)_

**Comment by benihime91** [comment]
Hmmm.... that's weird ... @alankritmishra Did you restart your runtime after installing pytorch-lightning ?

**Comment by alankritmishra** [comment]
Yes a couple of times, still didn't work. I am doing this experiment with
my custom dataset.

In the requirements you mentioned the version should not be more than
1.0.0. So, i didn't upgrade.

**Comment by benihime91** [comment]
You could probably try looking here for some solutions https://stackoverflow.com/questions/66538407/unable-to-import-pytorch-lightning-on-google-colab. It's seems its due to a version mismatch between pytorch and pytorch-lightning

**Comment by benihime91** [comment]
Colab has probably upgraded the default torch and torchvision version. 
```
torch>=1.6.0 torchvision>=0.7.0
```
You could try reinstalling the versions mentioned above. Or another way would be to uninstall `torchtext`.

**Comment by alankritmishra** [comment]
Okay let me try

**Comment by benihime91** [comment]
@alankritmishra I have updated the demo notebook. Should work on colab now. Do check it out.

**Comment by alankritmishra** [comment]
Thank you @benihime91 pytorch_lightning  imported successfully after uninstalling `torchtext `. However, it shows there on module called 'model' 

when I am trying `from model import RetinaNetModel`

**Comment by alankritmishra** [comment]
> Thank you @benihime91 pytorch_lightning imported successfully after uninstalling `torchtext `. However, it shows there on module called 'model'
> 
> when I am trying `from model import RetinaNetModel`

Should we have to track it as another issue?

**Comment by benihime91** [comment]
Did you try the new demo.ipynb notebook @alankritmishra ?

**Comment by alankritmishra** [comment]
Yes, and it worked, but I already have csv files for annonation and was trying your original documentation in github.

[Here ](https://colab.research.google.com/drive/1aItH_0GWI-30B8cpk4Inz5JN5XcWCTDf?usp=sharing) is my Colab notebook for your reference. Thanks again for such quick response.

**Comment by benihime91** [comment]
Hmmm.... You need to do 
```python
import sys
sys.path.append("/content/pytorch_retinanet/")
```
After cloning the repo and before importing modules from the RetinaNet repo itself.

Also you probably do not need to do 
```bash
pip install -r /content/pytorch_retinanet/requirements.txt
```
in colab because these lines are already doing that 

```python
!pip install -Uqq pytorch-lightning==1.0.0 omegaconf
!pip install -Uqq git+https://github.com/albumentations-team/albumentations
!pip uninstall torchtext
!git clone https://github.com/benihime91/pytorch_retinanet.git
```

**Comment by alankritmishra** [comment]
I came through that, Now I just have to mention the right path of my data in hparams.yaml.

It shows the below error:
FileNotFoundError: [Errno 2] No such file or directory: '/train/_annotations.csv'

Although, I already provide the root path in the `root_dir` placeholder

**Comment by alankritmishra** [comment]
Is there a way for the model to retrieve the data and annotation directly from my drive, or do I have to upload it on the runtime environment?

**Comment by benihime91** [comment]
You need provide the absolute path to the annotations. And `root_dir` is needed only for COCO datasets

**Comment by alankritmishra** [comment]
Hi @benihime91 the original issue is resolved so closing this tracker. Can I dm you for this to work?

**Comment by alankritmishra** [comment]
> Hi @benihime91 the original issue is resolved so closing this tracker. Can I dm you for this to work?

I have emailed you.
